// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrKZkQuNWwZJshsoj6ntxfLkWBrylLuao',
    appId: '1:636600687252:web:d4c0b65a85bd9902533281',
    messagingSenderId: '636600687252',
    projectId: 'flutter-test-77b5d',
    authDomain: 'flutter-test-77b5d.firebaseapp.com',
    storageBucket: 'flutter-test-77b5d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0JPkjmOo7IpPGYl2s91BIu1urp1KEbXw',
    appId: '1:636600687252:android:7184949832f2d52e533281',
    messagingSenderId: '636600687252',
    projectId: 'flutter-test-77b5d',
    storageBucket: 'flutter-test-77b5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaJGwUdQ4H37TTwpV652VJc_1TDSY4bXA',
    appId: '1:636600687252:ios:aade052b1ba25885533281',
    messagingSenderId: '636600687252',
    projectId: 'flutter-test-77b5d',
    storageBucket: 'flutter-test-77b5d.appspot.com',
    iosBundleId: 'com.julioap.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaJGwUdQ4H37TTwpV652VJc_1TDSY4bXA',
    appId: '1:636600687252:ios:80a9874f386eac1a533281',
    messagingSenderId: '636600687252',
    projectId: 'flutter-test-77b5d',
    storageBucket: 'flutter-test-77b5d.appspot.com',
    iosBundleId: 'com.julioap.crudFirebase.RunnerTests',
  );
}
